server:
  port: 8081
  servlet:
    context-path: /api

# PostgreSQL DataSource Configuration
spring:
  application:
    name: Staffi Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/staffi_backend
    username: postgres
    password: randompassword
    driver-class-name: org.postgresql.Driver
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    #show-sql: true
    #properties.hibernate.format_sql: true

security:
  jwt:
    token:
      secret-key: ""

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

